# Generated by Django 5.1.15 on 2026-07-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Nullable hanya untuk row bootstrap/sistem; row buatan user wajib mengisi ini.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Nullable hanya untuk row bootstrap/sistem; row buatan user wajib mengisi ini.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user'),
        ),
    ]
