# Generated by Django 5.1.15 on 2026-07-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0002_alter_organization_created_by_alter_user_created_by'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inspectionrecord',
            name='inspection_condition_state_null_iff_sensor_method',
        ),
        migrations.AddConstraint(
            model_name='inspectionrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('condition_state__isnull', True), ('method', 'sensor')), models.Q(models.Q(('method', 'sensor'), _negated=True), ('condition_state__isnull', False)), _connector='OR'), name='inspection_condition_state_null_iff_sensor_method'),
        ),
    ]
