# Generated by Django 5.1.15 on 2026-07-29 07:08

import apps.core.db_functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0002_alter_organization_created_by_alter_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwinModel',
            fields=[
                ('id', models.UUIDField(db_default=apps.core.db_functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model_format', models.CharField(choices=[('gltf', 'glTF')], default='gltf', max_length=10)),
                ('source', models.CharField(choices=[('drone_photogrammetry', 'Fotogrametri Drone'), ('manual', 'Manual'), ('fem_import', 'Import FEM')], max_length=32)),
                ('file_ref', models.CharField(help_text='SeaweedFS object key.', max_length=500)),
                ('version', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin_models', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, help_text='Nullable hanya untuk row bootstrap/sistem; row buatan user wajib mengisi ini.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'digitaltwin_digitaltwinmodel',
                'constraints': [models.UniqueConstraint(fields=('asset', 'version'), name='digitaltwinmodel_asset_version_unique')],
            },
        ),
    ]
