# Generated by Django 5.1.15 on 2026-07-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exportjob',
            new_name='exports_job_referen_4fc8c6_idx',
            old_name='exports_job_ref_type_idx',
        ),
    ]
