# Generated by Django 5.1.15 on 2026-07-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deterioration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='degradationforecast',
            new_name='deteriorati_model_i_2a4ca5_idx',
            old_name='deterior_model_i_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='deteriorationmodel',
            new_name='deteriorati_compone_ff1027_idx',
            old_name='deteriorat_compone_9e5f9c_idx',
        ),
    ]
