# Generated by Django 5.1.15 on 2026-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deterioration', '0002_rename_deterior_model_i_a1b2c3_idx_deteriorati_model_i_2a4ca5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degradationforecast',
            name='confidence_width',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Derived from fuzzy bounds (formulas.md §3.2). max_digits=6 (bukan 4) -- amandemen database.md §4: nilai ini selisih dua centroid() di skala condition_score 0-100, bisa melebihi 10 pada uncertainty tinggi; NUMERIC(4,3) overflow ditemukan saat membangun visualization.md §5 chart.', max_digits=6, null=True),
        ),
    ]
